// This file is auto-generated by generate-photo-manifest.js. Do not edit manually.

export const photoManifest: { [key: string]: string[] } = {
  "Amsterdam": [
    "assets/about/trips/Amsterdam/APC_1209.jpg",
    "assets/about/trips/Amsterdam/APC_1218.jpg",
    "assets/about/trips/Amsterdam/APC_1220.jpg",
    "assets/about/trips/Amsterdam/APC_1222.jpg",
    "assets/about/trips/Amsterdam/APC_1231.jpg",
    "assets/about/trips/Amsterdam/APC_1234.jpg"
  ],
  "Barcelona": [
    "assets/about/trips/Barcelona/IMG_5004.jpg",
    "assets/about/trips/Barcelona/IMG_5010.jpg",
    "assets/about/trips/Barcelona/IMG_5014.jpg",
    "assets/about/trips/Barcelona/IMG_5043.jpg",
    "assets/about/trips/Barcelona/IMG_5055.jpg",
    "assets/about/trips/Barcelona/IMG_5089.jpg"
  ],
  "Berlin": [
    "assets/about/trips/Berlin/APC_0608.jpg",
    "assets/about/trips/Berlin/APC_0612.jpg",
    "assets/about/trips/Berlin/APC_0654.jpg",
    "assets/about/trips/Berlin/APC_0673.jpg",
    "assets/about/trips/Berlin/APC_0682.jpg",
    "assets/about/trips/Berlin/IMG_6731.jpg"
  ],
  "Brussels": [
    "assets/about/trips/Brussels/20230818_090301.jpg",
    "assets/about/trips/Brussels/APC_0908.jpg",
    "assets/about/trips/Brussels/APC_0920.jpg"
  ],
  "Copenhagen": [
    "assets/about/trips/Copenhagen/APC_4466.jpg",
    "assets/about/trips/Copenhagen/APC_4478.jpg",
    "assets/about/trips/Copenhagen/APC_4496.jpg",
    "assets/about/trips/Copenhagen/APC_4532.jpg",
    "assets/about/trips/Copenhagen/APC_4560.jpg",
    "assets/about/trips/Copenhagen/APC_4625.jpg",
    "assets/about/trips/Copenhagen/APC_4628.jpg",
    "assets/about/trips/Copenhagen/APC_4639.jpg",
    "assets/about/trips/Copenhagen/APC_4641.jpg",
    "assets/about/trips/Copenhagen/APC_4647.jpg",
    "assets/about/trips/Copenhagen/APC_4668.jpg",
    "assets/about/trips/Copenhagen/APC_4740.jpg",
    "assets/about/trips/Copenhagen/APC_4822.jpg",
    "assets/about/trips/Copenhagen/APC_4835.jpg",
    "assets/about/trips/Copenhagen/APC_4839.jpg"
  ],
  "Edinburgh": [
    "assets/about/trips/Edinburgh/APC_1029.jpg",
    "assets/about/trips/Edinburgh/APC_1041.jpg",
    "assets/about/trips/Edinburgh/APC_1048.jpg",
    "assets/about/trips/Edinburgh/APC_1059.jpg",
    "assets/about/trips/Edinburgh/APC_1087.jpg",
    "assets/about/trips/Edinburgh/APC_1136.jpg",
    "assets/about/trips/Edinburgh/APC_1137.jpg",
    "assets/about/trips/Edinburgh/APC_1141.jpg"
  ],
  "Glasgow": [
    "assets/about/trips/Glasgow/APC_1165.jpg",
    "assets/about/trips/Glasgow/APC_1169.jpg",
    "assets/about/trips/Glasgow/IMG_0254.jpg"
  ],
  "Hamburg": [
    "assets/about/trips/Hamburg/APC_3590.jpg",
    "assets/about/trips/Hamburg/APC_3627.jpg",
    "assets/about/trips/Hamburg/APC_3628.jpg",
    "assets/about/trips/Hamburg/APC_3631.jpg",
    "assets/about/trips/Hamburg/APC_3648.jpg",
    "assets/about/trips/Hamburg/APC_3653.jpg",
    "assets/about/trips/Hamburg/APC_3691.jpg",
    "assets/about/trips/Hamburg/APC_3701.jpg",
    "assets/about/trips/Hamburg/APC_3752.jpg",
    "assets/about/trips/Hamburg/APC_3800.jpg",
    "assets/about/trips/Hamburg/APC_3841.jpg",
    "assets/about/trips/Hamburg/APC_3851.jpg",
    "assets/about/trips/Hamburg/APC_3870-Enhanced-NR.jpg",
    "assets/about/trips/Hamburg/APC_4939.jpg"
  ],
  "London": [
    "assets/about/trips/London/20230819_094928.jpg",
    "assets/about/trips/London/20230819_105150.jpg",
    "assets/about/trips/London/20230819_143219.jpg",
    "assets/about/trips/London/20230819_161013.jpg",
    "assets/about/trips/London/APC_0926.jpg",
    "assets/about/trips/London/APC_0928.jpg",
    "assets/about/trips/London/APC_1183.jpg",
    "assets/about/trips/London/APC_1190.jpg",
    "assets/about/trips/London/APC_1194.jpg"
  ],
  "Lund": [
    "assets/about/trips/Lund/APC_4226.jpg",
    "assets/about/trips/Lund/APC_4230.jpg",
    "assets/about/trips/Lund/APC_4232.jpg",
    "assets/about/trips/Lund/APC_4236.jpg",
    "assets/about/trips/Lund/APC_4248.jpg"
  ],
  "Mallorca": [
    "assets/about/trips/Mallorca/APC_2967.jpg",
    "assets/about/trips/Mallorca/APC_2982.jpg",
    "assets/about/trips/Mallorca/APC_2999.jpg",
    "assets/about/trips/Mallorca/APC_3002.jpg",
    "assets/about/trips/Mallorca/APC_3013.jpg",
    "assets/about/trips/Mallorca/APC_3130.jpg",
    "assets/about/trips/Mallorca/APC_3131.jpg",
    "assets/about/trips/Mallorca/APC_3191.jpg",
    "assets/about/trips/Mallorca/APC_3251.jpg",
    "assets/about/trips/Mallorca/APC_3307.jpg",
    "assets/about/trips/Mallorca/APC_3370.jpg",
    "assets/about/trips/Mallorca/APC_3511.jpg",
    "assets/about/trips/Mallorca/GPTempDownload.jpg"
  ],
  "Milan": [
    "assets/about/trips/Milan/APC_1449.jpg",
    "assets/about/trips/Milan/APC_1450.jpg",
    "assets/about/trips/Milan/APC_1477.jpg",
    "assets/about/trips/Milan/APC_1499.jpg",
    "assets/about/trips/Milan/APC_1503.jpg",
    "assets/about/trips/Milan/APC_1511.jpg",
    "assets/about/trips/Milan/IMG_0595.jpg"
  ],
  "NewYork": [
    "assets/about/trips/NewYork/0.jpg",
    "assets/about/trips/NewYork/1.jpg",
    "assets/about/trips/NewYork/10.jpg",
    "assets/about/trips/NewYork/11.jpg",
    "assets/about/trips/NewYork/12.jpg",
    "assets/about/trips/NewYork/13.jpg",
    "assets/about/trips/NewYork/14.jpg",
    "assets/about/trips/NewYork/15.jpg",
    "assets/about/trips/NewYork/16.jpg",
    "assets/about/trips/NewYork/17.jpg",
    "assets/about/trips/NewYork/18.jpg",
    "assets/about/trips/NewYork/2.jpg",
    "assets/about/trips/NewYork/3.jpg",
    "assets/about/trips/NewYork/4.jpg",
    "assets/about/trips/NewYork/5.jpg",
    "assets/about/trips/NewYork/6.jpg",
    "assets/about/trips/NewYork/7.jpg",
    "assets/about/trips/NewYork/8.jpg",
    "assets/about/trips/NewYork/9.jpg"
  ],
  "Paris": [
    "assets/about/trips/Paris/1.jpg",
    "assets/about/trips/Paris/APC_0417.jpg",
    "assets/about/trips/Paris/APC_0449.jpg",
    "assets/about/trips/Paris/APC_0508.jpg",
    "assets/about/trips/Paris/APC_0518.jpg",
    "assets/about/trips/Paris/APC_0568.jpg",
    "assets/about/trips/Paris/APC_0572.jpg",
    "assets/about/trips/Paris/APC_0573.jpg",
    "assets/about/trips/Paris/APC_0585.jpg",
    "assets/about/trips/Paris/IMG_6425.jpg"
  ],
  "Prague": [
    "assets/about/trips/Prague/0.jpg",
    "assets/about/trips/Prague/1.jpg",
    "assets/about/trips/Prague/2.jpg",
    "assets/about/trips/Prague/3.jpg",
    "assets/about/trips/Prague/4.jpg",
    "assets/about/trips/Prague/5.jpg",
    "assets/about/trips/Prague/6.jpg",
    "assets/about/trips/Prague/7.jpg",
    "assets/about/trips/Prague/8.jpg",
    "assets/about/trips/Prague/9.jpg"
  ],
  "Stockholm": [
    "assets/about/trips/Stockholm/APC_3945.jpg",
    "assets/about/trips/Stockholm/APC_3951.jpg",
    "assets/about/trips/Stockholm/APC_3962.jpg",
    "assets/about/trips/Stockholm/APC_3970.jpg",
    "assets/about/trips/Stockholm/APC_3985.jpg",
    "assets/about/trips/Stockholm/APC_3989.jpg",
    "assets/about/trips/Stockholm/APC_4035.jpg",
    "assets/about/trips/Stockholm/APC_4052.jpg",
    "assets/about/trips/Stockholm/APC_4064.jpg",
    "assets/about/trips/Stockholm/APC_4075.jpg",
    "assets/about/trips/Stockholm/APC_4076.jpg",
    "assets/about/trips/Stockholm/APC_4126.jpg",
    "assets/about/trips/Stockholm/APC_4199.jpg",
    "assets/about/trips/Stockholm/APC_4216.jpg"
  ],
  "Venice": [
    "assets/about/trips/Venice/APC_1325.jpg",
    "assets/about/trips/Venice/APC_1327.jpg",
    "assets/about/trips/Venice/APC_1345.jpg",
    "assets/about/trips/Venice/APC_1377.jpg",
    "assets/about/trips/Venice/APC_1380.jpg",
    "assets/about/trips/Venice/APC_1388.jpg",
    "assets/about/trips/Venice/APC_1389.jpg",
    "assets/about/trips/Venice/IMG_0481.jpg",
    "assets/about/trips/Venice/IMG_0506.jpg"
  ],
  "Ystad": [
    "assets/about/trips/Ystad/APC_4268.jpg",
    "assets/about/trips/Ystad/APC_4273.jpg",
    "assets/about/trips/Ystad/APC_4292.jpg",
    "assets/about/trips/Ystad/APC_4369.jpg",
    "assets/about/trips/Ystad/APC_4383.jpg"
  ]
};
